#!/bin/bash
if ! [ `ps aux| grep ${1} | grep rsync` ] ; then
	if [ `mount | grep ${1}` -gt "0" ] ; then
		lvm_post_backup ${1}
	fi
	lvcreate -L10G -s -n ${1}-snap /dev/xen-vol1/${1}-disk >/dev/null 2>&1
	mkdir /mnt/${1}
	mount /dev/xen-vol1/${1}-snap /mnt/${1}
else
	exit 1
fi
